CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE bookings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version bigint NOT NULL DEFAULT 0,
 user_id bigint NOT NULL,
 room_id bigint NOT NULL,
 start_time timestamp NOT NULL,
 end_time timestamp NOT NULL,
 purpose varchar(1000),
 status varchar(255) NOT NULL CHECK(status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED','NEEDS_REVIEW')),
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 CONSTRAINT booking_interval CHECK(start_time < end_time OR status = 'NEEDS_REVIEW'),
 CONSTRAINT no_room_overlap EXCLUDE USING gist (room_id WITH =, tsrange(start_time, greatest(start_time, end_time), '[)') WITH &&) WHERE (status IN ('PENDING','CONFIRMED'))
);
CREATE INDEX booking_user_time_idx ON bookings(user_id, start_time DESC, id DESC);
CREATE INDEX booking_room_time_idx ON bookings(room_id, start_time, end_time);
CREATE INDEX booking_expiry_idx ON bookings(end_time) WHERE status IN ('PENDING','CONFIRMED');
CREATE TABLE booking_outbox (
 event_id uuid PRIMARY KEY,
 booking_id bigint NOT NULL,
 user_id bigint NOT NULL,
 room_id bigint NOT NULL,
 kind varchar(40) NOT NULL,
 message varchar(1500) NOT NULL,
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 delivered_at timestamp,
 attempts integer NOT NULL DEFAULT 0,
 next_attempt_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX booking_outbox_pending_idx ON booking_outbox(next_attempt_at) WHERE delivered_at IS NULL;
CREATE TABLE legacy_import_audit (
 booking_id bigint PRIMARY KEY,
 original_status varchar(255),
 reason varchar(255) NOT NULL,
 imported_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
