CREATE TABLE rooms (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 room_number varchar(255) NOT NULL UNIQUE,
 name varchar(255) NOT NULL,
 type varchar(255) NOT NULL CHECK(type IN ('LECTURE_HALL','LABORATORY','COMPUTER_LAB','SEMINAR_ROOM','STUDY_ROOM')),
 capacity integer NOT NULL CHECK(capacity > 0),
 description varchar(1000),
 is_active boolean NOT NULL DEFAULT true,
 archived boolean NOT NULL DEFAULT false,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL
);
CREATE INDEX rooms_active_id_idx ON rooms(is_active, id);
