import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const env=Object.fromEntries(fs.readFileSync(process.env.TEST_SECRETS_FILE || '.local-test/harden.env','utf8').trim().split(/\r?\n/).map(l=>l.replace(/^\uFEFF/,'').split(/=(.*)/s).slice(0,2)));
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:8080';
let checks=0;
async function req(path,{token,method='GET',body,headers={}}={}) { const r=await fetch(base+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw}return {status:r.status,data}; }
function check(v,label){assert.ok(v,label);checks++;console.log('PASS '+label)}
for(const p of ['/api/users','/api/rooms','/api/bookings','/api/notifications','/api/subscriptions/rooms']) check((await req(p)).status===401,'anonymous denied '+p);
const login=await req('/api/auth/login',{method:'POST',body:{username:env.BOOTSTRAP_ADMIN_USERNAME,password:env.BOOTSTRAP_ADMIN_PASSWORD}});check(login.status===200,'secure bootstrap login'); const admin=login.data.token;
check((await req('/internal/users/1',{headers:{'X-Service-Token':env.INTERNAL_SERVICE_TOKEN}})).status===403,'internal gateway boundary');
const suffix=Date.now();const password=crypto.randomBytes(18).toString('hex');
const createUser=async(role)=>{const username=role.toLowerCase()+suffix;const u=await req('/api/users',{token:admin,method:'POST',body:{username,email:username+'@example.invalid',password,firstName:role==='TEACHER'?'Анна':'Иван',lastName:'Тестовый',role}});check(u.status===201||u.status===200,'create '+role);const l=await req('/api/auth/login',{method:'POST',body:{username,password}});check(l.status===200,'login '+role);return {...u.data,token:l.data.token,username,password};};
const teacher=await createUser('TEACHER'),student=await createUser('STUDENT');
check((await req('/api/users',{token:student.token})).status===403,'student cannot list profiles');
check(!JSON.stringify((await req('/api/users',{token:admin})).data).includes('password'),'password absent from DTO');
const room=await req('/api/rooms',{token:admin,method:'POST',body:{roomNumber:'T'+suffix,name:'Тестовая лаборатория',type:'LABORATORY',capacity:24,isActive:true,description:'Для проверки бронирования'}});check(room.status===201,'create room');
check((await req('/api/subscriptions/rooms/'+room.data.id,{token:student.token,method:'PUT'})).status===204,'subscribe');
const start=new Date(Date.now()+3*86400000).toISOString().slice(0,10)+'T10:00:00',end=start.slice(0,11)+'11:00:00';
const b={userId:teacher.id,roomId:room.data.id,startTime:start,endTime:end,purpose:'Конфиденциальная тема'};
check((await req('/api/bookings',{token:student.token,method:'POST',body:b})).status===403,'student cannot book');
const results=await Promise.all(Array.from({length:5},()=>req('/api/bookings',{token:teacher.token,method:'POST',body:b})));
console.log('concurrency statuses',results.map(r=>r.status)); check(results.filter(r=>r.status===201).length===1,'one winner under concurrency'); const booking=results.find(r=>r.status===201).data;
const publicB=await req('/api/bookings/'+booking.id,{token:student.token});check(publicB.data.userId===null&&publicB.data.purpose==='Занятие','other users see occupancy only');
const page=await req('/api/bookings?size=1',{token:teacher.token});check(page.data.content.length===1&&page.data.totalPages>=1,'paginated history');
check((await req('/api/bookings?size=101',{token:teacher.token})).status===400,'bounded page size');
check((await req('/api/bookings?userId='+teacher.id,{token:student.token})).status===403,'private user filter');
const gql=await req('/graphql',{token:teacher.token,method:'POST',body:{query:'{ me { id username } rooms { id } bookings(size: 1) { content { id } totalElements } }'}});console.log('graphql',JSON.stringify(gql));check(gql.status===200&&!gql.data.errors,'GraphQL queries');
check((await req('/api/bookings/'+booking.id+'/cancel',{token:teacher.token,method:'POST'})).status===204,'cancel own booking');
await new Promise(r=>setTimeout(r,3000));const notices=await req('/api/notifications',{token:student.token});check(notices.data.content?.length>=2,'watcher gets durable events');
check((await req('/api/notifications/'+notices.data.content[0].id+'/read',{token:teacher.token,method:'POST'})).status===404,'cannot read another user notification');
check((await req('/api/notifications/'+notices.data.content[0].id+'/read',{token:student.token,method:'POST'})).status===204,'mark own notification');
check((await req('/api/rooms/'+room.data.id,{token:admin,method:'DELETE'})).status===204,'archive room');
check((await req('/api/rooms/'+room.data.id,{token:teacher.token})).data.archived===true,'room retained');
check((await req('/api/bookings/'+booking.id,{token:admin})).status===200,'booking history retained');
check((await req('/api/users/'+student.id,{token:admin,method:'DELETE'})).status===204,'archive user');
check((await req('/api/rooms',{token:student.token})).status===401,'archived token revoked');
fs.writeFileSync('.local-test/harden-test-session.json',JSON.stringify({admin,teacher,student,room:room.data,booking}));
console.log('TOTAL '+checks);
