CREATE TABLE notifications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id uuid NOT NULL,
 user_id bigint NOT NULL,
 booking_id bigint NOT NULL,
 room_id bigint NOT NULL,
 kind varchar(40) NOT NULL,
 message varchar(1500) NOT NULL,
 is_read boolean NOT NULL DEFAULT false,
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(event_id, user_id)
);
CREATE INDEX notification_user_time_idx ON notifications(user_id, id DESC);
CREATE TABLE room_subscriptions (
 user_id bigint NOT NULL,
 room_id bigint NOT NULL,
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id, room_id)
);
CREATE TABLE received_events (
 event_id uuid PRIMARY KEY,
 received_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
