apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels: {app: user-service}
  template:
    metadata:
      labels: {app: user-service}
    spec:
      containers:
      - name: user-service
        image: audit/user-service:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_ADDRESS
          value: "0.0.0.0"
        - name: JAVA_TOOL_OPTIONS
          value: "-Duser.timezone=Europe/Moscow"
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        - name: ROOM_SERVICE_URL
          value: "http://room-service:8082"
        - name: BOOKING_SERVICE_URL
          value: "http://booking-service:8083"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:8084"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/audit_users"
        - name: SPRING_DATASOURCE_USERNAME
          value: "audit_users"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: USER_DB_PASSWORD
        - name: INTERNAL_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: INTERNAL_SERVICE_TOKEN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: JWT_SECRET
        - name: BOOTSTRAP_ADMIN_ENABLED
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: BOOTSTRAP_ADMIN_ENABLED
        - name: BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: BOOTSTRAP_ADMIN_USERNAME
        - name: BOOTSTRAP_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: BOOTSTRAP_ADMIN_EMAIL
        - name: BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: BOOTSTRAP_ADMIN_PASSWORD
        readinessProbe:
          httpGet: {path: /actuator/health, port: 8081}
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests: {memory: 256Mi, cpu: 100m}
          limits: {memory: 768Mi, cpu: "1"}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector: {app: user-service}
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
