CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(255) NOT NULL UNIQUE,
 email varchar(255) NOT NULL UNIQUE,
 password varchar(255) NOT NULL,
 first_name varchar(255) NOT NULL,
 last_name varchar(255) NOT NULL,
 role varchar(255) NOT NULL CHECK(role IN ('ADMIN','TEACHER','STUDENT')),
 active boolean NOT NULL DEFAULT true,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL
);
CREATE INDEX users_active_id_idx ON users(active, id);
